name: Testes Automatizados

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit-tests:
    name: 🧪 Testes Unitários
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configura Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instala dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Roda testes unitários
        run: |
          pytest -m unit

  integration-tests:
    name: 🔗 Testes de Integração
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configura Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instala dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Roda testes de integração
        run: |
          pytest -m integration
